#pragma once

enum class EndTurnState
{
	STATE_NONE,
	STATE_DRAW_FIRST_CARD,
	STATE_DRAW_SECOND_CARD,
	STATE_WAIT_FOR_FIRST_DISCARD,
	STATE_WAIT_FOR_SECOND_DISCARD,
	STATE_DO_INFECTIONS,
	STATE_FIRST_EPIDEMIC,
	STATE_SECOND_EPIDEMIC
};